### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by openpaul** [ZhangZhenmiao/METAMVGL#1]
Hello,

it seems to me like it would be nice to have sensible default parameters for the settings:

```
  --max_iter MAX_ITER   max iteration
  --thresh THRESH       stop threshold
```

What would be good values and how would I determine them?

**Comment by ZhangZhenmiao** [comment]
Hi,

Thanks. It's a very helpful suggestion. 
I have updated the default settings of these two parameters.

```--max_iter``` is the maximum number of iterations to update the graph weights and contig labels. ```--thresh``` is the minimum value of the reduced ratio of the objective function. Because the iterations are always convergent (according to [this paper](https://www.ijcai.org/Proceedings/16/Papers/269.pdf)), bigger ```--max_iter``` (default 100) and smaller ```--thresh``` (default 0.00000001) are recommended.

> Hello,
> 
> it seems to me like it would be nice to have sensible default parameters for the settings:
> 
> ```
>   --max_iter MAX_ITER   max iteration
>   --thresh THRESH       stop threshold
> ```
> 
> What would be good values and how would I determine them?

**Comment by openpaul** [comment]
Thank you. Thats very helpful.
