### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by schorlton** [ZhangZhenmiao/METAMVGL#10]
Thanks for the great tool. I'm hoping this is enough info to identify the root cause of the issue but I may be able to create mock data that can reproduce if needed. I suspect this is related to not enough edges in the graph or all contigs isolated? Thanks again!

```bash
# prep graph
Start loading fastg ...
--
Loaded 95 nodes, 0 links.
Done.
Start parsing alignments ...
Parsed 3185360 lines ...
Done.
Start constructing PE overlap ...
Constructed PE overlap of 16 paths, new overlaps 38 ...
Done.
Start traversing assembly graph ...
Traversed edge neighbours of 95 paths ...
Done.
Start traversing PE graph ...
Traversed PE neighbours of 95 paths ...
Done.
 
# run METAMVGL
METAMVGL.py --contigs final.contigs.fa --assembler MEGAHIT --assembly_graph metamvgl_out.ag --PE_graph metamvgl_out.pe --binned temp.csv --output temp_output

initial binned contigs: 95
binned contigs after remove ambiguous: 95
non isolated contigs: 3
non isolated binned contigs: 3
 
Traceback (most recent call last):
File "/usr/local/bin/METAMVGL.py", line 224, in <module>
F_u = sp.sparse.linalg.inv(sp.sparse.eye(all_trans_uu.shape[0], format='csc', dtype=np.float64) - all_trans_uu).dot(all_trans_ul).dot(F_l)
File "/opt/conda/envs/test/lib/python3.10/site-packages/scipy/sparse/linalg/_matfuncs.py", line 75, in inv
Ainv = spsolve(A, I)
File "/opt/conda/envs/test/lib/python3.10/site-packages/scipy/sparse/linalg/_dsolve/linsolve.py", line 306, in spsolve
sparse_data = np.concatenate(data_segs)
File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate
```

**Comment by ZhangZhenmiao** [comment]
Thank you! The assembly graph (line 3 of your log) has no edges. This might be the error reason. Does the fastg file in your assembly output folder looks weird?

**Comment by schorlton** [comment]
You are correct - I think the assembly graph just has no edges when I go back and review. It otherwise looks normal. Is there any value to running METAMVGL on this sample (eg. could it still leverage the paired-end graph?) or should:
a. I check the graph for edges before calling METAMVGL and skip if there are no edges or
b. METAMVGL print a warning and exit?

Thanks again.

**Comment by ZhangZhenmiao** [comment]
After checking the code, I think only the empty assembly graph could not stop METAMVGL from leveraging the paired-end graph. The problem for this sample might be there are no unbinned non-isolated contigs (in your log: non isolated contigs: 3; non isolated binned contigs: 3), which leads to some zero matrices and causes errors in the sp.sparse.linalg.inv function.

For such cases, METAMVGL cannot perform label propagation since all the non-isolated contigs are labeled in the initial binning results. I modified the codes to skip this error. Please let me know if the bug disappears after this update.

Thank you!
Zhenmiao

**Comment by schorlton** [comment]
That worked, thanks!
