### ISSUE TITLE
one question

### ISSUE THREAD

**Issue by yuyuyu-fy** [ZhangZhenmiao/METAMVGL#3]
please tell me where is prep_graph ?how can I use it to get 2 graph of PE? I can't find the py of  prep_graph,thanks.

**Comment by ZhangZhenmiao** [comment]
Hi,

prep_graph is created by `make` command. It will compile the cpp code using the instructions in  `Makefile`. Did your `make` command fail to build prep_graph?

**Comment by yuyuyu-fy** [comment]
Hello, thanks for your reply. I'm sorry for my late here. I'm a freshman. I don't know how to use makefile. for input contigs to get the output of the two graphs what I need. It have any requirement files or parameter suffixes? Thank you very much for your answer!

**Comment by ZhangZhenmiao** [comment]
Hello,

Thanks for using METAMVGL.

You can use `prep_graph` to generate the 2 graphs. To build `prep_graph`, [htslib](https://github.com/samtools/htslib) is needed because I use `-lhts` in the `Makefile`. So the steps to get the 2 graphs are:

Step 1.
Follow the instructions [here](https://github.com/samtools/htslib/blob/develop/INSTALL) to install the htslib. After the installation, you can find two folders named "include" and “lib” under the installation location of htslib (the installation location can be specified using `--prefix` when building htslib). 

You need to add the absolute path of "include" to the environmental variable `$CPLUS_INCLUDE_PATH`, by appending `export CPLUS_INCLUDE_PATH=<absolute_path_to_include>:$CPLUS_INCLUDE_PATH` to ~/.bashrc.

Also, the absolute path of "lib" should be added to both `$LIBRARY_PATH` and `$LD_LIBRARY_PATH`, by appending `export LIBRARY_PATH=<absolute_path_to_lib>:$LIBRARY_PATH` and `export LD_LIBRARY_PATH=<absolute_path_to_lib>:$LD_LIBRARY_PATH` to ~/.bashrc.

Step 2.
Download the code of METAMVGL using `git clone https://github.com/ZhangZhenmiao/METAMVGL.git`. Then enter the folder `METAMVGL`, and execute the command `make`. When the `make` command finishes, you can find the exectuable file `prep_graph` under the `METAMVGL` folder. You might want to add `prep_graph` to the environmental variable `$PATH`, by appending `export PATH=<absolute_path_to_METAMVGL_folder>:$PATH` to ~/.bashrc.

Step 3.
Now you can use `prep_graph` to create the two graphs. For example, if your contigs were generated by [metaSPAdes](https://github.com/ablab/spades), you can use `prep_graph -a metaSPAdes -p contigs.paths -g assembly_graph.fastg -b align.spades.bam -o graph_output` (you can find `contigs.paths` and `assembly_graph.fastg` under the output folder of `metaSPAdes`; `align.spades.bam` is the bam file created by aligning reads to the contigs) to get the two graphs.

I hope this helps you.

**Comment by yuyuyu-fy** [comment]
Thanks for your reply. I'm sorry for late here. When I run the make. command, it shows such a problem. How can I solve it? I'm a freshman. Thank you for your reply！
<img width="573" alt="image" src="https://user-images.githubusercontent.com/75973865/112302142-b3f48000-8cd5-11eb-9061-753e714b5ceb.png">

**Comment by ZhangZhenmiao** [comment]
Hi,

What happens if “cd /Users/fuyu/Desktop/METAMVGL-main/“ before “make”?

**Comment by yuyuyu-fy** [comment]
Thank you so much! I've been able to successfully run prep_graph, but I don't know where to get **align.spades.bam** My spades output doesn't have this file, but the others are ready. Do I need some software to run aligning reads? Sorry, I don't know what the data is, because I haven't used BAM before. Thank you again! Many thanks for all your answers!

**Comment by yuyuyu-fy** [comment]
I guess it was created by some add-on program in the spades, right？

**Comment by ZhangZhenmiao** [comment]
Hello, The following is only my suggestions. you can use the [bwa](https://github.com/lh3/bwa) software to create `align.spades.bam`, by executing the command `bwa mem -t <threads> <spades_output_folder>/contigs.fasta <reads_used_in_spades_assembly> | samtools sort -@ <threads> -o align.spades.bam`. For more details of bwa, you can refer the documentation of bwa [here](https://github.com/lh3/bwa). The subsequential [samtools sort](http://www.htslib.org/doc/samtools-sort.html) command is to transfer the output of bwa to a coordinate-sorted bam file, which is the common way to store the alignment result in the disk.
